### ISSUE TITLE
No route to host, DVL might be booting? [Errno 113] No route to host

### ISSUE THREAD

**Issue by jonatansw** [waterlinked/dvl-a50-ros-driver#5]
Hi,

After a while of the DVL being powered on (between 10 minutes and sometimes a couple of hours) it will create the error message **No route to host, DVL might be booting? [Errno 113] No route to host**. Also the web interface stops working when this starts to happen and it is no longer possible to ping the DVL.
The error remains until the power is disconnected and connected again.
Do you have any idea what could cause this, if it is something on our side or if it is a potential bug?
Thanks in advance,

**Comment by wlkh** [comment]
Hi,

Please make sure you have the latest software release (1.4.2 at the time of writing). There was a bug in the 1.3.x releases where the TCP would stop responding after some time. If you are still having issues, please contact Water Linked support.
