### ISSUE TITLE
Error with updated DVL firmware 

### ISSUE THREAD

**Issue by IgnacioCarlucho** [waterlinked/dvl-a50-ros-driver#8]
With the updated firmware of the DVL you now get an error when trying to run the publisher as presented in the repo. 

I believe this is caused because with the updated firmware the raw_data recieved consists of two different types of JSON packages: the velocity report and the dead reckoning report. So when runing the following lines: 

```
data = json.loads(raw_data)
pub_raw.publish(raw_data)
theDVL.time = data["time"]
```
you get an error if the raw_data recieved is of the dead reckoning type, as the *time* variable is not on that package type. 

I think a simple fix would be to just check which type of message you recieved, and ignore it if it is a position message. But I think a better solution would be to also publish the dead reckoning position.

**Comment by incebellipipo** [comment]
Hi Ignacio,

You might want to take a look at our repository: https://github.com/GSO-soslab/waterlinked_dvl_ros
I've tested it with firmware v2.0.8, Ubuntu 20.04 and ROS Noetic.

**Comment by IgnacioCarlucho** [comment]
Hi incebellipipo, 

Thanks for sharing! 
My branch of the driver is also updated: https://github.com/IgnacioCarlucho/dvl-a50-ros-driver 
Altough it has some modifications specific to our system. So I still think it will be good if the driver gets updated here.

**Comment by water-linked-richard-williamson** [comment]
Hi, thank you for reporting this! It should now be fixed. For now the dead reckoning messages are just ignored, but we will look into publishing them when we have a chance :-).
